# Generated by Django 4.0.6 on 2022-08-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_meal_end_time_alter_meal_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
