# Generated by Django 4.0.6 on 2022-08-08 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0004_alter_meal_end_time_alter_meal_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
