# Generated by Django 4.0.6 on 2022-07-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
