# Generated by Django 4.0.6 on 2022-07-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_is_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_approver',
            new_name='is_supervisor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_viewer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_supervisor',
        ),
    ]
