# Generated by Django 4.0.6 on 2022-07-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_is_approver_user_is_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
