# Generated by Django 4.0.6 on 2022-08-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=50, unique=True)),
                ('doc', models.FileField(upload_to='forms')),
            ],
        ),
    ]
