# Generated by Django 4.0.6 on 2022-07-15 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_userprofile_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField(verbose_name='reason for overtime')),
                ('start_time', models.TimeField(default='16:30:00')),
                ('end_time', models.TimeField(default='16:30:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_sheet_approved_by', to='users.userprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_sheet_created_by', to='users.userprofile')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
                ('multiplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overtime.multiplier')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_sheet_updated_by', to='users.userprofile')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_sheet_verified_by', to='users.userprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
