# Generated by Django 4.0.6 on 2022-07-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiplier',
            options={'ordering': ('multiplier',)},
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='end_time',
            field=models.TimeField(default='18:30:00'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='start_time',
            field=models.TimeField(default='16tmux:30:00'),
        ),
    ]
