# Generated by Django 4.0.6 on 2022-07-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_alter_timesheet_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
